### ISSUE TITLE
Duplicate entry 'XXX' for key 'UNQ_SALES_FLAT_ORDER_INCREMENT_ID''

### ISSUE THREAD

**Issue by acharrex** [acharrex/magento-core-ce#7]
L'erreur suivante est loguée sur le store RWD pour l'ensemble des 1.9:

```
2015-05-20T16:25:26+00:00 ERR (3): 
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '400000001' for key 'UNQ_SALES_FLAT_ORDER_INCREMENT_ID'' in C:\xampp\htdocs\salesids\core\community\1.9.1.1\lib\Zend\Db\Statement\Pdo.php:228
Stack trace:
#0 C:\xampp\htdocs\salesids\core\community\1.9.1.1\lib\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\salesids\core\community\1.9.1.1\lib\Varien\Db\Statement\Pdo\Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Zend\Db\Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 C:\xampp\htdocs\salesids\core\community\1.9.1.1\lib\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 C:\xampp\htdocs\salesids\core\community\1.9.1.1\lib\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `sa...', Array)
#5 C:\xampp\htdocs\salesids\core\community\1.9.1.1\lib\Varien\Db\Adapter\Pdo\Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `sa...', Array)
#6 C:\xampp\htdocs\salesids\core\community\1.9.1.1\lib\Zend\Db\Adapter\Abstract.php(576): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `sa...', Array)
#7 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Core\Model\Resource\Db\Abstract.php(453): Zend_Db_Adapter_Abstract->insert('sales_flat_orde...', Array)
#8 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Sales\Model\Resource\Order\Abstract.php(425): Mage_Core_Model_Resource_Db_Abstract->save(Object(Mage_Sales_Model_Order))
#9 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Core\Model\Abstract.php(318): Mage_Sales_Model_Resource_Order_Abstract->save(Object(Mage_Sales_Model_Order))
#10 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Core\Model\Resource\Transaction.php(151): Mage_Core_Model_Abstract->save()
#11 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Sales\Model\Service\Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#12 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Sales\Model\Service\Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#13 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Checkout\Model\Type\Onepage.php(784): Mage_Sales_Model_Service_Quote->submitAll()
#14 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Checkout\controllers\OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#15 [internal function]: Mage_Checkout_OnepageController->saveOrderAction()
#16 C:\xampp\htdocs\salesids\extensions\fastcheckout\community\1.9.1.1\app\code\community\SalesIds\FastCheckout\controllers\Checkout\OnepageController.php(200): call_user_func(Array)
#17 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Core\Controller\Varien\Action.php(407): SalesIds_FastCheckout_Checkout_OnepageController->preDispatch()
#18 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#19 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#20 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#21 C:\xampp\htdocs\salesids\core\community\1.9.1.1\app\Mage.php(684): Mage_Core_Model_App->run(Array)
#22 C:\xampp\htdocs\salesids\core\community\1.9.1.1\index.php(87): Mage::run('', 'store')
#23 {main}
```

**Comment by acharrex** [comment]
Bug fixé sur toutes les bases 1.9.X.
